language: python

env:
  - PYTHON=2.7 PANDAS=0.17.0
  - PYTHON=2.7 PANDAS=0.18.0
  - PYTHON=3.4 PANDAS=0.16.0
  - PYTHON=3.4 PANDAS=0.17.0
  - PYTHON=3.5 PANDAS=0.18.0 COVERAGE=true

addons:
  apt:
    packages:
    - graphviz

install:
  - bash scripts/build_travis.sh

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

script:
  - export PATH="$HOME/miniconda/bin:$PATH"
  - source activate myenv
  - python -m nose --with-coverage --cover-package=pydetect
  - flake8 --ignore E501 pydetect

after_success:
  - if [ "$COVERAGE" ]; then
      coveralls;
    fi
